name: Create a release
description: Creates a release on Github and tags the code
author: "habakke@matrise.net"

inputs:
  version:
    required: true
    description: Release version
  pre_release:
    type: boolean
    default: false
    description: Pre-release?
  github_token:
    required: false
    description: The secrets.GITHUB_TOKEN

runs:
  using: "composite"
  steps:
    - name: Create release
      uses: "actions/github-script@v6"
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          try {
            const version = '${{ inputs.version }}'
            const response = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: `Release ${version}`,
              owner: context.repo.owner,
              prerelease: ${{ inputs.pre_release == 'true' }},
              repo: context.repo.repo,
              tag_name: version,
            });
            core.exportVariable('RELEASE_ID', response.data.id);
            core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
          } catch (error) {
            core.setFailed(error.message);
          }