name: Development pipeline
on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to run against
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
      image: ${{ steps.build.outputs.image }}
      dockerfile: ${{ steps.build.outputs.dockerfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: habakke/github-actions/.github/actions/auth-github@v1
        id: auth-github
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: habakke/github-actions/.github/actions/docker-build@v1
        id: build
        with:
          repository: ${{ vars.DOCKER_REPO }}
          image_name: ${{ vars.DOCKER_IMAGE }}
          dockerfile: ./Dockerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}


  terraform-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Terraform variables
        shell: bash
        run: |
          echo "TF_VAR_project_id=${{ vars.DEPLOY_PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_environment=development" >> $GITHUB_ENV
          echo "TF_VAR_container=${{ needs.docker-build.outputs.tags }}" >> $GITHUB_ENV
      - uses: habakke/github-actions/.github/actions/auth-gcp@master
        id: auth-gcp
        with:
          repository: ${{ vars.DOCKER_REPO }}
          service_account_key: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}
      - uses: habakke/github-actions/.github/actions/terraform-deploy-gcp@master
        with:
          directory: ./deploy/development
          repository: ${{ vars.DOCKER_REPO }}
          service_account_key: ${{ vars.DEPLOY_SERVICE_ACCOUNT_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}