name: Build and publish a Docker image to Github GHCR
description: Builds and pushes a docker image to a Github hosted docker repository
author: "habakke@matrise.net"

inputs:
  repository:
    required: true
    description: The repository to deploy to
  image_name:
    required: true
    description: Name of docker image to build and publish
  tag:
    required: false
    description: Optional tag to apply to the docker image
  dockerfile:
    required: true
    default: ./Dockerfile
    description: The docker file to use when building the image
  platforms:
    required: false
    default: linux/amd64
    description: The platforms to build for
  github_token:
    required: true
    description: A token used by the Dockerfile

runs:
  using: "composite"
  steps:
    - name: Login to GitHub GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.repository }}/${{ inputs.image_name }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,enable=true,priority=100,prefix=,suffix=,format=long

    - name: Debug tags
      shell: bash
      run: |
        echo "TAGS: ${{ steps.metadata.outputs.tags }}"
        echo "LABELS: ${{ steps.metadata.outputs.labels }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx to enable caching
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

    - name: Generate job summary
      shell: bash
      run: |
        echo "Built docker image:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Name:  ${{ inputs.repository }}/${{ inputs.image_name }}" >> $GITHUB_STEP_SUMMARY        
        echo "- TAGS: ${{ steps.metadata.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "- LABELS: ${{ steps.metadata.outputs.labels }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
